Stat svc
green-rail/java-explore-with-me pull request #3
Opened 2023-08-27 13:58 UTC by green-rail

2023-08-28 09:39 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые стоит исправить!

Желаю удачи!

2023-08-28 09:39 UTC, LexLippi commented on statistics/service/src/main/java/ru/practicum/explore/controller/StatisticsController.java
> +    public List<ViewStatsDto> getStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Стоит использовать константу

2023-08-28 09:39 UTC, LexLippi commented on statistics/service/src/main/java/ru/practicum/explore/controller/StatisticsController.java
> +                                       @RequestParam(required = false) String[] uris,
По возможности лучше использовать более удобную абстракцию - `java.util.List`
Более того, можно также использовать дефолтное значение

2023-08-28 09:39 UTC, LexLippi commented on statistics/client/src/main/java/ru/practicum/explore/client/StatClient.java
> +        return start.isBefore(end);
можно упростить выражение:

```java
return !start.isAfter(LocalDateTime.now()) && start.isBefore(end);
```

2023-08-29 05:15 UTC, green-rail commented
Исправил, спасибо за ревью!

2023-08-29 22:08 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи со следующими этапами диплома!

2023-08-30 10:16 UTC, merged